branch-defaults:
  default:
    environment: flask-env
    group_suffix: null
global:
  application_name: flockApp
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null

[aws:elasticbeanstalk:container:python]
  NumProcesses=1
  NumThreads=15
  StaticFiles=/static/.*=
  WSGIPath=flockApp/application.py
